version: '2'

services:
  db:
    image: twistedbrew/twistedbrew
    command:
      - python
      - manage.py
      - syncdb
      - --noinput
  master:
    image: twistedbrew/twistedbrew
    volumes_from:
      - db
    command:
      - python
      - -u
      - manage.py
      - twisted_brew
      - ./config/master.yml
  worker:
    image: twistedbrew/twistedbrew
    environment:
      MASTER_IP: "master"
    links:
      - master
    volumes_from:
      - db
    command:
      - python
      - -u
      - manage.py
      - twisted_brew
      - ./config/mash_config.yml
  ui:
    image: twistedbrew/twistedbrew
    environment:
      MASTER_IP: "master"
    links:
      - master
    ports:
      - 8000:8000
    volumes_from:
      - db
    command:
      - python
      - -u
      - manage.py
      - runserver
      - 0.0.0.0:8000