global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'twistedbrew-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'consul'
    static_configs:
      - targets: ['localhost:9107']