communication:
    ip: "localhost"
    port: "5672"
    master_queue: "MasterQueue"
    broadcast_exchange: "TwistedBrewBroadcast"

master:
    name: "Twisted Brewer"

workers:
    - worker:
        name: "Mash Dude"
        class: "core.workers.mash.MashWorker"
        outputs:
            - output:
                name: "Mash Tun"
                device: "core.devices.ssr.SSR"
                io: "gpio0"
                active: "False"
                callback: "mash_heating_callback"
                cycle_time: "10.0"
        inputs:
            - input:
                name: "Temperature"
                device: "Probe"
                io: "gpio1"
                active: "True"
                callback: "mash_temperature_callback"
                cycle_time: "10.0"
