#master:
#    name: "BrewMaster"
#    ip: "localhost"
#    port: "5672"

workers:
    - worker:
        name: "Mash Dude"
        ip: "localhost"
        port: "5672"
        class: "MashWorker"
        outputs:
            - output:
                name: "Mash Tun"
                type: "SSR"
                io: "gpio0"
        inputs:
            - input:
                name: "Temperature"
                type: "Probe"
                io: "gpio1"
