communication:
    ip: "192.168.1.65"
    master_port: "9991"
    worker_port: "9992"

master:
    name: "BrewMaster"

workers:
    - worker:
        name: "Fermat"
        class: "core.workers.fermentation.FermentationWorker"
        simulation: "True"
        outputs:
            - output:
                name: "Fermenter"
                device_class: "core.devices.ssr.SSR"
                io: "gpio4"
                active: "False"
                callback: "fermentation_heating_callback"
                cycle_time: "10.0"
        inputs:
            - input:
                name: "Temperature"
                device_class: "core.devices.probe.Probe"
                io: "gpio5"
                active: "False"
                callback: "fermentation_temperature_callback"
                cycle_time: "10.0"
